export type SourceDocument={id:string;name:string;type:'sample'|'text'|'markdown';createdAt:string;size:number};
export type DocumentChunk={id:string;documentId:string;title:string;text:string;tags:string[];position:number};
export const sampleDocuments:SourceDocument[]=[
{id:'architecture',name:'Product Architecture Brief',type:'sample',createdAt:'2026-09-21',size:8420},
{id:'security',name:'Tenant Security Notes',type:'sample',createdAt:'2026-09-21',size:6210},
{id:'retrieval',name:'Retrieval Evaluation Notes',type:'sample',createdAt:'2026-09-21',size:7340}];
export const sampleChunks:DocumentChunk[]=[
{id:'architecture-01',documentId:'architecture',title:'System boundaries',text:'The application separates retrieval, orchestration and answer production. Core owns domain rules, application coordinates the use case, and adapters provide external capabilities.',tags:['architecture','boundaries'],position:1},
{id:'architecture-02',documentId:'architecture',title:'Provider boundary',text:'The answer provider is an interface. The reference implementation uses a deterministic provider, while a future LLM adapter can be introduced without changing retrieval or domain code.',tags:['provider','llm','architecture'],position:2},
{id:'security-01',documentId:'security',title:'Tenant isolation',text:'Every request carries a tenant context. Application services resolve data through tenant-aware repositories. PostgreSQL row-level security provides a second enforcement boundary using tenant_id.',tags:['tenant','security','database','rls'],position:1},
{id:'security-02',documentId:'security',title:'Authorization',text:'Permissions are evaluated before data mutations. The browser can hide unavailable actions for clarity, but authorization and isolation must be enforced again on the server.',tags:['permissions','security','authorization'],position:2},
{id:'retrieval-01',documentId:'retrieval',title:'Chunking strategy',text:'Documents are split into stable chunks with source metadata. Chunk boundaries should preserve enough local context to make retrieved evidence understandable.',tags:['chunks','retrieval','context'],position:1},
{id:'retrieval-02',documentId:'retrieval',title:'Ranking',text:'The reference retriever scores normalized query terms against title, content and tags. The trace exposes candidate scores and selected chunks so relevance decisions are inspectable.',tags:['ranking','retrieval','trace'],position:2},
{id:'retrieval-03',documentId:'retrieval',title:'Insufficient context',text:'When no relevant evidence is retrieved, the system should say so instead of inventing an answer. Retrieval confidence is a signal, not proof of correctness.',tags:['grounding','confidence','safety'],position:3}];