import'./style.css';
import{extractTextFromPdf}from'./infrastructure/pdf';import{addTextDocument,ask,createWorkspace,type WorkspaceState}from'./application/ask';
let state:WorkspaceState=createWorkspace();let last:any=ask('How is tenant isolation enforced?',state);let history:{q:string;r:any}[]=[];const root=document.querySelector('#app')!;
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
function render(){const docs=state.documents.map(d=>'<button class="doc" data-doc="'+d.id+'"><span>'+esc(d.name)+'</span><small>'+d.type+' · '+state.chunks.filter(c=>c.documentId===d.id).length+' chunks</small></button>').join('');
const hits=last.hits.map((h:any)=>'<article class="source"><div><b>'+esc(h.chunk.title)+'</b><span>'+Math.round(h.score*100)+'%</span></div><p>'+esc(h.chunk.text)+'</p><small>Source: '+esc(state.documents.find(d=>d.id===h.chunk.documentId)?.name??h.chunk.documentId)+' · matched: '+h.matched.join(', ')+'</small></article>').join('')||'<div class="empty">No evidence selected.</div>';
const trace=last.trace.selected.map((x:any,i:number)=>'<div class="trace-row"><i>0'+(i+1)+'</i><div><b>'+esc(x.title)+'</b><small>'+x.id+' · score '+x.score+' · terms '+x.matched.join(', ')+'</small></div></div>').join('');
const chats=history.slice(-5).map(x=>'<div class="history"><b>'+esc(x.q)+'</b><p>'+esc(x.r.answer.text)+'</p></div>').join('');
root.innerHTML='<main><header><div><strong>ASK A DOCUMENT</strong><span> / retrieval workspace</span></div><a href="https://github.com/gespitia/ask-a-document">Repository ↗</a></header><section class="hero"><div><label>LOCAL RAG REFERENCE IMPLEMENTATION</label><h1>Ask the evidence,<br><em>not the guess.</em></h1><p>Upload text, retrieve grounded passages, inspect the ranking trace, and see exactly which source fragments shaped the answer.</p></div><div class="stats"><b>'+state.documents.length+'<small>documents</small></b><b>'+state.chunks.length+'<small>chunks</small></b><b>'+last.trace.latencyMs+'ms<small>last retrieval</small></b></div></section><section class="grid"><aside class="panel library"><div class="panel-head"><div><label>01 · LIBRARY</label><h2>Documents</h2></div><button id="upload">+ Add file</button><input id="file" type="file" accept=".pdf,.txt,.md,application/pdf,text/plain,text/markdown" hidden></div>'+docs+'<button id="reset" class="subtle">Reset sample workspace</button></aside><section class="panel research"><label>02 · RESEARCH</label><h2>Question</h2><textarea id="question" placeholder="Ask about architecture, security, retrieval...">'+esc(last.question)+'</textarea><div class="askbar"><button id="ask">Run retrieval</button><span>Provider: deterministic · local only</span></div><div class="answer"><div class="answer-meta"><span>GROUNDED ANSWER</span><b>'+Math.round(last.answer.confidence*100)+'% retrieval confidence</b></div><p>'+esc(last.answer.text)+'</p><div class="chips">'+last.answer.sources.map((s:string)=>'<span>'+s+'</span>').join('')+'</div></div><label>CONVERSATION</label>'+ (chats||'<div class="empty">Your last questions will appear here.</div>')+'</section></section><section class="lower"><div class="panel"><div class="panel-head"><div><label>03 · EVIDENCE</label><h2>Retrieved sources</h2></div><span class="muted">'+last.hits.length+' selected</span></div>'+hits+'</div><div class="panel"><div class="panel-head"><div><label>04 · TRACE</label><h2>Retrieval trace</h2></div><span class="muted">'+last.trace.provider+'</span></div><div class="trace">'+trace+'</div><div class="architecture"><b>Pipeline</b><span>Question → Retriever → Ranker → Context → Provider</span></div></div></section><footer>Browser-only reference implementation. No external LLM call. The provider boundary is designed so a real model adapter can be introduced without coupling it to retrieval.</footer></main>';
root.querySelector('#ask')!.addEventListener('click',()=>{const q=(root.querySelector('#question') as HTMLTextAreaElement).value.trim();if(!q)return;last=ask(q,state);history.push({q,r:last});render()});
root.querySelector('#upload')!.addEventListener('click',()=>root.querySelector<HTMLInputElement>('#file')!.click());
root.querySelector('#file')!.addEventListener('change',async e=>{const f=(e.target as HTMLInputElement).files?.[0];if(!f)return;try{const isPdf=f.type==='application/pdf'||f.name.toLowerCase().endsWith('.pdf');const text=isPdf?await extractTextFromPdf(f):await f.text();if(!text.trim())throw new Error('No readable text was found in this file.');addTextDocument(state,f.name,text,f.name.toLowerCase().endsWith('.md')?'markdown':'text');last=ask('What is this document about?',state);render()}catch(error){const message=error instanceof Error?error.message:'Could not read the file.';alert(message)}});
root.querySelector('#reset')!.addEventListener('click',()=>{localStorage.removeItem('ask-document-workspace');state=createWorkspace();last=ask('How is tenant isolation enforced?',state);history=[];render()});}
render();